# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'fd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import ui_fd3
import cv2
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_fdtest(object):
    def setupUi(self, fdtest):
        fdtest.setObjectName("fdtest")
        fdtest.resize(376, 559)
        self.buttonBox = QtWidgets.QDialogButtonBox(fdtest)
        self.buttonBox.setGeometry(QtCore.QRect(10, 500, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.graphicsView = QtWidgets.QGraphicsView(fdtest)
        self.graphicsView.setGeometry(QtCore.QRect(40, 20, 211, 401))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(fdtest)
        self.pushButton.setGeometry(QtCore.QRect(90, 450, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(fdtest)
        self.buttonBox.accepted.connect(fdtest.accept) # type: ignore
        self.buttonBox.rejected.connect(fdtest.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(fdtest)
        self.setLayout(self.__layout_main)  # 到这步才会显示所有控件
    def retranslateUi(self, fdtest):
        _translate = QtCore.QCoreApplication.translate
        fdtest.setWindowTitle(_translate("fdtest", "Dialog"))
        self.pushButton.setText(_translate("fdtest", "Open"))
